# Site settings
title: ranchtronix
description: > # this means to ignore newlines until "baseurl:"
  RaNchTr0n1x wiki
baseurl: "/ranchtronix" # the subpath of your site, e.g. /blog/
url: "http://bitstream.io" # the base hostname & protocol for your site

# Build settings
highlighter: pygments
markdown: kramdown

#the "none" style is an alias for /:categories/:title.html
permalink: none
