# Site settings
title: ranchtronix
description: > # this means to ignore newlines until "baseurl:"
  RaNchTr0n1x wiki
#baseurl: "/ranchtronix" # the subpath of your site, e.g. /blog/
url: "http://ranchtronix.org" # the base hostname & protocol for your site
github_repository_url: https://github.com/rajbot/ranchtronix

# Build settings
highlighter: pygments
markdown: kramdown

#the "none" style is an alias for /:categories/:title.html
permalink: none
